// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: graft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigUpdate_Phase int32

const (
	ConfigUpdate_LEARNING ConfigUpdate_Phase = 0
	ConfigUpdate_JOINT    ConfigUpdate_Phase = 1
	ConfigUpdate_APPLIED  ConfigUpdate_Phase = 2
)

// Enum value maps for ConfigUpdate_Phase.
var (
	ConfigUpdate_Phase_name = map[int32]string{
		0: "LEARNING",
		1: "JOINT",
		2: "APPLIED",
	}
	ConfigUpdate_Phase_value = map[string]int32{
		"LEARNING": 0,
		"JOINT":    1,
		"APPLIED":  2,
	}
)

func (x ConfigUpdate_Phase) Enum() *ConfigUpdate_Phase {
	p := new(ConfigUpdate_Phase)
	*p = x
	return p
}

func (x ConfigUpdate_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigUpdate_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_graft_proto_enumTypes[0].Descriptor()
}

func (ConfigUpdate_Phase) Type() protoreflect.EnumType {
	return &file_graft_proto_enumTypes[0]
}

func (x ConfigUpdate_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigUpdate_Phase.Descriptor instead.
func (ConfigUpdate_Phase) EnumDescriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{8, 0}
}

type LogEntry_Type int32

const (
	LogEntry_COMMAND LogEntry_Type = 0
	LogEntry_NOOP    LogEntry_Type = 1
	LogEntry_CONFIG  LogEntry_Type = 2
)

// Enum value maps for LogEntry_Type.
var (
	LogEntry_Type_name = map[int32]string{
		0: "COMMAND",
		1: "NOOP",
		2: "CONFIG",
	}
	LogEntry_Type_value = map[string]int32{
		"COMMAND": 0,
		"NOOP":    1,
		"CONFIG":  2,
	}
)

func (x LogEntry_Type) Enum() *LogEntry_Type {
	p := new(LogEntry_Type)
	*p = x
	return p
}

func (x LogEntry_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntry_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_graft_proto_enumTypes[1].Descriptor()
}

func (LogEntry_Type) Type() protoreflect.EnumType {
	return &file_graft_proto_enumTypes[1]
}

func (x LogEntry_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntry_Type.Descriptor instead.
func (LogEntry_Type) EnumDescriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{9, 0}
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_graft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{0}
}

func (x *RequestVoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_graft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntriesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Term              int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          string                 `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex      int64                  `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm       int64                  `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries           []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIndex int64                  `protobuf:"varint,6,opt,name=leaderCommitIndex,proto3" json:"leaderCommitIndex,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_graft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommitIndex() int64 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_graft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_graft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *SnapshotRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *SnapshotRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *SnapshotRequest) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_graft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type SnapshotMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex int64                  `protobuf:"varint,1,opt,name=lastIncludedIndex,proto3" json:"lastIncludedIndex,omitempty"`
	LastIncludedTerm  int64                  `protobuf:"varint,2,opt,name=lastIncludedTerm,proto3" json:"lastIncludedTerm,omitempty"`
	Size              int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ConfigUpdate      *ConfigUpdate          `protobuf:"bytes,4,opt,name=configUpdate,proto3" json:"configUpdate,omitempty"`
	ConfigUpdateIndex int64                  `protobuf:"varint,5,opt,name=configUpdateIndex,proto3" json:"configUpdateIndex,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_graft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotMetadata) GetLastIncludedIndex() int64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *SnapshotMetadata) GetLastIncludedTerm() int64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *SnapshotMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SnapshotMetadata) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		return x.ConfigUpdate
	}
	return nil
}

func (x *SnapshotMetadata) GetConfigUpdateIndex() int64 {
	if x != nil {
		return x.ConfigUpdateIndex
	}
	return 0
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_graft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{7}
}

func (x *NodeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Old           []*NodeConfig          `protobuf:"bytes,1,rep,name=old,proto3" json:"old,omitempty"`
	New           []*NodeConfig          `protobuf:"bytes,2,rep,name=new,proto3" json:"new,omitempty"`
	Phase         ConfigUpdate_Phase     `protobuf:"varint,3,opt,name=phase,proto3,enum=graft.ConfigUpdate_Phase" json:"phase,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_graft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigUpdate) GetOld() []*NodeConfig {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *ConfigUpdate) GetNew() []*NodeConfig {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *ConfigUpdate) GetPhase() ConfigUpdate_Phase {
	if x != nil {
		return x.Phase
	}
	return ConfigUpdate_LEARNING
}

func (x *ConfigUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Type          LogEntry_Type          `protobuf:"varint,4,opt,name=type,proto3,enum=graft.LogEntry_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_graft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogEntry) GetType() LogEntry_Type {
	if x != nil {
		return x.Type
	}
	return LogEntry_COMMAND
}

type PersistedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTerm   int64                  `protobuf:"varint,1,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	VotedFor      string                 `protobuf:"bytes,2,opt,name=votedFor,proto3" json:"votedFor,omitempty"`
	CommitIndex   int64                  `protobuf:"varint,3,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistedState) Reset() {
	*x = PersistedState{}
	mi := &file_graft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedState) ProtoMessage() {}

func (x *PersistedState) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedState.ProtoReflect.Descriptor instead.
func (*PersistedState) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{10}
}

func (x *PersistedState) GetCurrentTerm() int64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *PersistedState) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

func (x *PersistedState) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

type WalRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Crc32         uint32                 `protobuf:"varint,3,opt,name=crc32,proto3" json:"crc32,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_graft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{11}
}

func (x *WalRecord) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WalRecord) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

func (x *WalRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WalSegmentHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         uint64                 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	SegmentNumber int32                  `protobuf:"varint,4,opt,name=segmentNumber,proto3" json:"segmentNumber,omitempty"`
	FirstIndex    int64                  `protobuf:"varint,5,opt,name=firstIndex,proto3" json:"firstIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalSegmentHeader) Reset() {
	*x = WalSegmentHeader{}
	mi := &file_graft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalSegmentHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalSegmentHeader) ProtoMessage() {}

func (x *WalSegmentHeader) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalSegmentHeader.ProtoReflect.Descriptor instead.
func (*WalSegmentHeader) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{12}
}

func (x *WalSegmentHeader) GetMagic() uint64 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *WalSegmentHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WalSegmentHeader) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *WalSegmentHeader) GetSegmentNumber() int32 {
	if x != nil {
		return x.SegmentNumber
	}
	return 0
}

func (x *WalSegmentHeader) GetFirstIndex() int64 {
	if x != nil {
		return x.FirstIndex
	}
	return 0
}

type WalSegmentTrailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         uint64                 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalSegmentTrailer) Reset() {
	*x = WalSegmentTrailer{}
	mi := &file_graft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalSegmentTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalSegmentTrailer) ProtoMessage() {}

func (x *WalSegmentTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalSegmentTrailer.ProtoReflect.Descriptor instead.
func (*WalSegmentTrailer) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{13}
}

func (x *WalSegmentTrailer) GetMagic() uint64 {
	if x != nil {
		return x.Magic
	}
	return 0
}

var File_graft_proto protoreflect.FileDescriptor

const file_graft_proto_rawDesc = "" +
	"\n" +
	"\vgraft.proto\x12\x05graft\"\x90\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x03R\vlastLogTerm\"K\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\"\xe5\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\tR\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x01(\x03R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x01(\x03R\vprevLogTerm\x12)\n" +
	"\aentries\x18\x05 \x03(\v2\x0f.graft.LogEntryR\aentries\x12,\n" +
	"\x11leaderCommitIndex\x18\x06 \x01(\x03R\x11leaderCommitIndex\"E\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xb6\x01\n" +
	"\x0fSnapshotRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\tR\bleaderId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.graft.SnapshotMetadataR\bmetadata\"&\n" +
	"\x10SnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\"\xe7\x01\n" +
	"\x10SnapshotMetadata\x12,\n" +
	"\x11lastIncludedIndex\x18\x01 \x01(\x03R\x11lastIncludedIndex\x12*\n" +
	"\x10lastIncludedTerm\x18\x02 \x01(\x03R\x10lastIncludedTerm\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x127\n" +
	"\fconfigUpdate\x18\x04 \x01(\v2\x13.graft.ConfigUpdateR\fconfigUpdate\x12,\n" +
	"\x11configUpdateIndex\x18\x05 \x01(\x03R\x11configUpdateIndex\".\n" +
	"\n" +
	"NodeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xc8\x01\n" +
	"\fConfigUpdate\x12#\n" +
	"\x03old\x18\x01 \x03(\v2\x11.graft.NodeConfigR\x03old\x12#\n" +
	"\x03new\x18\x02 \x03(\v2\x11.graft.NodeConfigR\x03new\x12/\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x19.graft.ConfigUpdate.PhaseR\x05phase\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"-\n" +
	"\x05Phase\x12\f\n" +
	"\bLEARNING\x10\x00\x12\t\n" +
	"\x05JOINT\x10\x01\x12\v\n" +
	"\aAPPLIED\x10\x02\"\x9d\x01\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.graft.LogEntry.TypeR\x04type\")\n" +
	"\x04Type\x12\v\n" +
	"\aCOMMAND\x10\x00\x12\b\n" +
	"\x04NOOP\x10\x01\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x02\"p\n" +
	"\x0ePersistedState\x12 \n" +
	"\vcurrentTerm\x18\x01 \x01(\x03R\vcurrentTerm\x12\x1a\n" +
	"\bvotedFor\x18\x02 \x01(\tR\bvotedFor\x12 \n" +
	"\vcommitIndex\x18\x03 \x01(\x03R\vcommitIndex\"I\n" +
	"\tWalRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x14\n" +
	"\x05crc32\x18\x03 \x01(\rR\x05crc32\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x9e\x01\n" +
	"\x10WalSegmentHeader\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\x04R\x05magic\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x12$\n" +
	"\rsegmentNumber\x18\x04 \x01(\x05R\rsegmentNumber\x12\x1e\n" +
	"\n" +
	"firstIndex\x18\x05 \x01(\x03R\n" +
	"firstIndex\")\n" +
	"\x11WalSegmentTrailer\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\x04R\x05magic2\xde\x01\n" +
	"\x04Raft\x12D\n" +
	"\vRequestVote\x12\x19.graft.RequestVoteRequest\x1a\x1a.graft.RequestVoteResponse\x12J\n" +
	"\rAppendEntries\x12\x1b.graft.AppendEntriesRequest\x1a\x1c.graft.AppendEntriesResponse\x12D\n" +
	"\x0fInstallSnapshot\x12\x16.graft.SnapshotRequest\x1a\x17.graft.SnapshotResponse(\x01B!Z\x1fgithub.com/mizosoft/graft/pb;pbb\x06proto3"

var (
	file_graft_proto_rawDescOnce sync.Once
	file_graft_proto_rawDescData []byte
)

func file_graft_proto_rawDescGZIP() []byte {
	file_graft_proto_rawDescOnce.Do(func() {
		file_graft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graft_proto_rawDesc), len(file_graft_proto_rawDesc)))
	})
	return file_graft_proto_rawDescData
}

var file_graft_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_graft_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_graft_proto_goTypes = []any{
	(ConfigUpdate_Phase)(0),       // 0: graft.ConfigUpdate.Phase
	(LogEntry_Type)(0),            // 1: graft.LogEntry.Type
	(*RequestVoteRequest)(nil),    // 2: graft.RequestVoteRequest
	(*RequestVoteResponse)(nil),   // 3: graft.RequestVoteResponse
	(*AppendEntriesRequest)(nil),  // 4: graft.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 5: graft.AppendEntriesResponse
	(*SnapshotRequest)(nil),       // 6: graft.SnapshotRequest
	(*SnapshotResponse)(nil),      // 7: graft.SnapshotResponse
	(*SnapshotMetadata)(nil),      // 8: graft.SnapshotMetadata
	(*NodeConfig)(nil),            // 9: graft.NodeConfig
	(*ConfigUpdate)(nil),          // 10: graft.ConfigUpdate
	(*LogEntry)(nil),              // 11: graft.LogEntry
	(*PersistedState)(nil),        // 12: graft.PersistedState
	(*WalRecord)(nil),             // 13: graft.WalRecord
	(*WalSegmentHeader)(nil),      // 14: graft.WalSegmentHeader
	(*WalSegmentTrailer)(nil),     // 15: graft.WalSegmentTrailer
}
var file_graft_proto_depIdxs = []int32{
	11, // 0: graft.AppendEntriesRequest.entries:type_name -> graft.LogEntry
	8,  // 1: graft.SnapshotRequest.metadata:type_name -> graft.SnapshotMetadata
	10, // 2: graft.SnapshotMetadata.configUpdate:type_name -> graft.ConfigUpdate
	9,  // 3: graft.ConfigUpdate.old:type_name -> graft.NodeConfig
	9,  // 4: graft.ConfigUpdate.new:type_name -> graft.NodeConfig
	0,  // 5: graft.ConfigUpdate.phase:type_name -> graft.ConfigUpdate.Phase
	1,  // 6: graft.LogEntry.type:type_name -> graft.LogEntry.Type
	2,  // 7: graft.Raft.RequestVote:input_type -> graft.RequestVoteRequest
	4,  // 8: graft.Raft.AppendEntries:input_type -> graft.AppendEntriesRequest
	6,  // 9: graft.Raft.InstallSnapshot:input_type -> graft.SnapshotRequest
	3,  // 10: graft.Raft.RequestVote:output_type -> graft.RequestVoteResponse
	5,  // 11: graft.Raft.AppendEntries:output_type -> graft.AppendEntriesResponse
	7,  // 12: graft.Raft.InstallSnapshot:output_type -> graft.SnapshotResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_graft_proto_init() }
func file_graft_proto_init() {
	if File_graft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graft_proto_rawDesc), len(file_graft_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graft_proto_goTypes,
		DependencyIndexes: file_graft_proto_depIdxs,
		EnumInfos:         file_graft_proto_enumTypes,
		MessageInfos:      file_graft_proto_msgTypes,
	}.Build()
	File_graft_proto = out.File
	file_graft_proto_goTypes = nil
	file_graft_proto_depIdxs = nil
}
