// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: graft.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Graft_Append_FullMethodName = "/graft.Graft/Append"
)

// GraftClient is the client API for Graft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraftClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
}

type graftClient struct {
	cc grpc.ClientConnInterface
}

func NewGraftClient(cc grpc.ClientConnInterface) GraftClient {
	return &graftClient{cc}
}

func (c *graftClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, Graft_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraftServer is the server API for Graft service.
// All implementations must embed UnimplementedGraftServer
// for forward compatibility.
type GraftServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	mustEmbedUnimplementedGraftServer()
}

// UnimplementedGraftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraftServer struct{}

func (UnimplementedGraftServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedGraftServer) mustEmbedUnimplementedGraftServer() {}
func (UnimplementedGraftServer) testEmbeddedByValue()               {}

// UnsafeGraftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraftServer will
// result in compilation errors.
type UnsafeGraftServer interface {
	mustEmbedUnimplementedGraftServer()
}

func RegisterGraftServer(s grpc.ServiceRegistrar, srv GraftServer) {
	// If the following call pancis, it indicates UnimplementedGraftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Graft_ServiceDesc, srv)
}

func _Graft_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraftServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Graft_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraftServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Graft_ServiceDesc is the grpc.ServiceDesc for Graft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Graft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graft.Graft",
	HandlerType: (*GraftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Graft_Append_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graft.proto",
}
